---
dependency:
  name: galaxy
  enabled: true
  options:
    role-file: molecule/default/requirements.yml
driver:
  name: docker
lint: |
  ansible-lint
platforms:
  - name: rhel8
    image: registry.access.redhat.com/ubi8/ubi-init
    dns_servers:
      - 1.1.1.1
      - 9.9.9.9
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/usr/sbin/init"
    security_opts:
      - seccomp=unconfined
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    prepare: prepare.yml
verifier:
  name: ansible
