name: Molecule Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: converge
        env:
          ANSIBLE_FORCE_COLOR: '1'
